#!/usr/bin/env node
// Builds the capture acceptance report from the raw captures in data/raw.
//
//   node analyze.mjs [--date YYYY-MM-DD] [--out ../../data/raw/<date>-capture-report.md]
//
// Everything in the report is computed from responses/, decoded/ and manifest.json
// (the on-screen DOM extraction made at capture time). Nothing is typed in by hand.

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const args = parseArgs(process.argv.slice(2));
const RAW = path.resolve(here, '../../data/raw');
const SOURCES = JSON.parse(await fs.readFile(path.join(here, 'sources.json'), 'utf8'));
const DATE = args.date || (await latestDate());
const OUT = path.resolve(here, args.out || path.join(RAW, `${DATE}-capture-report.md`));

const caps = [];
for (const s of SOURCES) {
  const dir = path.join(RAW, s.slug, DATE);
  try {
    const manifest = JSON.parse(await fs.readFile(path.join(dir, 'manifest.json'), 'utf8'));
    caps.push(await load(s, dir, manifest));
  } catch (e) {
    caps.push({ source: s, dir, missing: true, error: String(e.message || e) });
  }
}

const md = [];
const H = (s) => md.push('', s, '');
const P = (s) => md.push(s);
const CODE = (s, lang = '') => md.push('```' + lang, s, '```');
const TABLE = (head, rows) => { md.push('| ' + head.join(' | ') + ' |', '| ' + head.map(() => '---').join(' | ') + ' |'); for (const r of rows) md.push('| ' + r.map(cell).join(' | ') + ' |'); };
const cell = (v) => String(v ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');

H(`# Capture acceptance report — ${DATE}`);
P(`Generated by \`tools/capture/analyze.mjs\` from \`data/raw/<source>/${DATE}/\`. Every number below is computed from the saved raw files and the manifest's on-screen DOM extraction; nothing is hand-typed. Non-menu data (account, ordering and location configuration, contact details) is not part of the capture; each manifest lists what was removed (removed, redactions).`);
P('');
TABLE(['#', 'Source', 'Captured at', 'JSON responses', 'Screenshots', 'HTML', 'Skipped', 'Redactions', 'Errors'],
  caps.map((c) => c.missing ? [c.source.n, c.source.slug, 'MISSING: ' + c.error, '', '', '', '', '', ''] : [c.source.n, c.source.slug, c.manifest.capturedAt, c.manifest.counts.responses, c.manifest.counts.screenshots, c.manifest.counts.html, c.manifest.counts.skipped, c.manifest.counts.redactions, c.manifest.counts.errors]));
for (const c of caps.filter((c) => !c.missing && (c.manifest.redactions.length || c.manifest.errors.length || c.manifest.skipped.length))) {
  P('');
  P(`**${c.source.slug}** — skipped: ${JSON.stringify(c.manifest.skipped)}; redactions: ${JSON.stringify(c.manifest.redactions)}; errors: ${JSON.stringify(c.manifest.errors)}`);
}

// ---------------------------------------------------------------------------
H('## 1. Category names on screen vs. in the captured data');
for (const c of caps) {
  if (c.missing) { P(`### [${c.source.n}] ${c.source.slug}\n\nMISSING capture: ${c.error}`); continue; }
  P(`### [${c.source.n}] ${c.source.slug}`);
  P('');
  if (c.kind === 'mealsy') {
    P(`Data file: \`${c.menuFile}\` (gunzipped copy of \`${c.menuRawFile}\`). The payload holds ${c.menus.length} menu(s): ${c.menus.map((m) => `"${m.name}" (channels ${m.channels}; ${m.sections.length} sections; ${m.itemCount} items${m.isDefault ? '; IsDefaultOnlineMenu' : ''})`).join('; ')}.`);
    P('');
    P(`Menu rendered on screen (best match of on-screen section titles and item names): **"${c.menu.name}"** — ${c.menuMatch.matched}/${c.observedTitles.length} on-screen section titles and ${c.menuMatch.itemsMatched}/${c.screenNames.length} on-screen item names found in it. Other menus score: ${c.menus.filter((m) => m !== c.menu).map((m) => { const names = new Set(m.sections.flatMap((s) => s.items.map((i) => norm(i.name)))); return `"${m.name}" ${c.screenNames.filter((n) => names.has(n)).length}/${c.screenNames.length}`; }).join(', ')}.`);
    P('');
    TABLE(['On-screen category (nav bar)', 'On-screen section title', 'In data (section name)', 'Match'],
      c.observedNav.map((nav, i) => { const title = c.observedTitles[i] ?? ''; const sec = c.menu.sections.find((s) => norm(s.name) === norm(title)); return [nav, title, sec ? sec.name : '— MISSING —', sec ? 'yes' : 'NO']; }));
    const missing = c.observedTitles.filter((t) => !c.menu.sections.some((s) => norm(s.name) === norm(t)));
    const extra = c.menu.sections.filter((s) => !c.observedTitles.some((t) => norm(t) === norm(s.name)));
    P('');
    P(missing.length ? `**INCOMPLETE: ${missing.length} on-screen categories are not in the data: ${missing.join(', ')}**` : `**PASS: every on-screen category (${c.observedTitles.length}) is present in the captured data.**`);
    if (extra.length) P(`Sections in the data that are not on screen: ${extra.map((s) => `"${s.name}" (${s.items.length} items, Status ${s.status})`).join('; ')}.`);
  } else {
    const onScreen = c.categories.filter((k) => !k.hidden);
    const hidden = c.categories.filter((k) => k.hidden);
    P(`Data file: \`html/index.html\` (rendered DOM). Categories are Elementor heading widgets; on-screen means rendered on the iPhone viewport (not inside an \`elementor-hidden-mobile\` block).`);
    P('');
    TABLE(['Category (heading text)', 'On screen (phone)', 'In data (HTML)'], c.categories.map((k) => [k.name, k.hidden ? 'no (hidden on phone)' : 'yes', 'yes']));
    P('');
    P(`**PASS: every on-screen category (${onScreen.length}) is in the captured HTML.** ${hidden.length ? `${hidden.length} categor${hidden.length === 1 ? 'y is' : 'ies are'} in the HTML but hidden on the phone layout: ${hidden.map((k) => k.name).join(', ')}.` : ''}`);
  }
  P('');
}

// ---------------------------------------------------------------------------
H('## 2. Item count per category and items with no price');
for (const c of caps.filter((c) => !c.missing)) {
  P(`### [${c.source.n}] ${c.source.slug}`);
  P('');
  if (c.kind === 'mealsy') {
    TABLE(['Section (data)', 'Items in data', 'Items on screen', 'No price (data)', 'No price (screen)', 'Items with photo URL', 'Items with modifier groups'],
      c.menu.sections.map((s) => { const obs = c.observedSections.find((o) => norm(o.title) === norm(s.name)); return [s.name, s.items.length, obs ? obs.items.length : '—', s.items.filter((i) => i.price == null || i.price === 0).length, obs ? obs.items.filter((i) => !/\d/.test(i.price || '')).length : '—', s.items.filter((i) => i.photo).length, s.items.filter((i) => i.modifierGroups.length).length]; }));
    P('');
    P(`Totals — data: ${c.menu.itemCount} items in ${c.menu.sections.length} sections; on screen: ${c.manifest.observed.itemCountOnScreen} items in ${c.observedSections.length} sections; no price in data: ${c.menu.sections.flatMap((s) => s.items).filter((i) => i.price == null || i.price === 0).length}.`);
    if (c.dataNotOnScreen.length) P(`Items in the data but not rendered on screen: ${c.dataNotOnScreen.map(({ section, item }) => `${section} › ${item.name} (${item.price}, Status ${item.status}${c.availabilityIds?.has(item.id) ? ', id present in dataCategory=2 availability list' : ''})`).join('; ')}.`);
    if (c.screenNotInData.length) P(`Items on screen but not in the matched menu: ${c.screenNotInData.join('; ')}.`);
    const noPrice = c.menu.sections.flatMap((s) => s.items.filter((i) => i.price == null || i.price === 0).map((i) => `${s.name} › ${i.name} (Price=${JSON.stringify(i.price)})`));
    if (noPrice.length) P(`No-price items: ${noPrice.join('; ')}`);
    if (c.availability) P(`\`dataCategory=2\` lists ${c.availability.items} MenuItemSalesAvailabilities and ${c.availability.modifiers} ModifierSalesAvailabilities entries; ${c.availability.matched} of the item ids match items in the rendered menu. The meaning of this list is not documented by Mealsy and is not used for anything here.`);
  } else {
    TABLE(['Category', 'On screen (phone)', 'Items', 'No price', 'Items with size variants', 'Notes'],
      c.categories.map((k) => [k.name, k.hidden ? 'hidden' : 'yes', k.items.length, k.items.filter((i) => !i.prices.length).length, k.items.filter((i) => i.variants?.length).length, k.notes.join(' / ')]));
    P('');
    const all = c.categories.flatMap((k) => k.items);
    P(`Totals — ${all.length} items in ${c.categories.length} categories; ${all.filter((i) => !i.prices.length).length} with no price${c.source.n === 6 ? ' (this page shows no prices at all, as expected)' : ''}.`);
    if (c.source.n !== 6) { const np = c.categories.flatMap((k) => k.items.filter((i) => !i.prices.length).map((i) => `${k.name} › ${i.name}`)); if (np.length) P(`No-price items: ${np.join('; ')}`); }
  }
  P('');
}

// ---------------------------------------------------------------------------
H('## 3. Verbatim records for the named items');
const wanted = [
  { name: 'Senso Waffle', sources: [1, 2, 6] },
  { name: 'Bazari Koobideh Kebab', sources: [3, 4] },
  { name: 'Barg Kebab', sources: [3, 4] },
  { name: 'Mohtasham', sources: [3, 4] },
  { name: 'Red Wine Sangria', sources: [3, 5] },
];
for (const w of wanted) {
  P(`### "${w.name}"`);
  P('');
  for (const c of caps.filter((c) => !c.missing)) {
    const hits = findItems(c, w.name);
    if (!hits.length) { if (w.sources.includes(c.source.n)) P(`- [${c.source.n}] ${c.source.slug}: **not found** (no item name contains "${w.name}" in the data; searched ${c.kind === 'mealsy' ? 'every menu in the payload' : 'every widget'}).`); continue; }
    for (const h of hits) {
      P(`- [${c.source.n}] ${c.source.slug} — ${h.where}:`);
      CODE(h.verbatim, h.lang);
    }
  }
  P('');
}

// ---------------------------------------------------------------------------
H('## 4. Sources 1 vs 2 (ro-SensoCafe vs SensoCafe)');
{
  const a = caps.find((c) => c.source.n === 1), b = caps.find((c) => c.source.n === 2);
  if (!a || !b || a.missing || b.missing) P('One of the two captures is missing; comparison not possible.');
  else {
    const byUrl = (c) => Object.fromEntries(c.manifest.files.filter((f) => f.type === 'response' && /mymealsy/.test(f.url)).map((f) => [f.url.replace(/^https?:\/\/[^/]+/, ''), f]));
    const ua = byUrl(a), ub = byUrl(b);
    TABLE(['Mealsy request (path + query)', 'Source 1 sha256', 'Source 2 sha256', 'Same bytes'], Object.keys({ ...ua, ...ub }).map((u) => [u, ua[u]?.sha256.slice(0, 16) ?? '—', ub[u]?.sha256.slice(0, 16) ?? '—', ua[u] && ub[u] ? (ua[u].sha256 === ub[u].sha256 ? 'yes' : 'NO') : 'n/a']));
    P('');
    P(`Business account/location ids — source 1: ${a.account.BusinessAccountId} / ${a.account.BusinessLocationId}; source 2: ${b.account.BusinessAccountId} / ${b.account.BusinessLocationId}. Rendered menu — source 1: "${a.menu.name}" with ${a.menu.itemCount} items in ${a.menu.sections.length} sections; source 2: "${b.menu.name}" with ${b.menu.itemCount} items in ${b.menu.sections.length} sections. On screen — source 1: ${a.manifest.observed.itemCountOnScreen} items; source 2: ${b.manifest.observed.itemCountOnScreen} items.`);
    P('');
    const sample = a.menu.sections.flatMap((s) => s.items).filter((_, i) => i % Math.max(1, Math.floor(a.menu.itemCount / 10)) === 0).slice(0, 10);
    TABLE(['Item id', 'Source 1: name / price / description', 'Source 2: name / price / description', 'Identical'], sample.map((i) => { const j = b.menu.sections.flatMap((s) => s.items).find((x) => x.id === i.id); const f = (x) => x ? `${x.name} / ${x.price} / ${x.description ?? 'null'}` : '— not present —'; return [i.id, f(i), f(j), j && f(i) === f(j) ? 'yes' : 'NO']; }));
    P('');
    P('Rows marked n/a are requests the app fired in only one of the two runs (timing of the idle wait); they are not menu data.');
    P('');
    P(a.decodedMenuSha === b.decodedMenuSha ? `**Same menu: the decoded \`dataCategory=1\` payloads are byte-identical (sha256 ${a.decodedMenuSha.slice(0, 16)}…).**` : `**Different payloads: decoded \`dataCategory=1\` sha256 ${a.decodedMenuSha.slice(0, 16)}… vs ${b.decodedMenuSha.slice(0, 16)}…** (see the sample diff above).`);
  }
}

// ---------------------------------------------------------------------------
H('## 5. Image URLs referenced per source');
TABLE(['#', 'Source', 'Unique image URLs', 'From DOM', 'From JSON responses', 'Menu items with a photo URL in the data', 'Downloaded'],
  caps.filter((c) => !c.missing).map((c) => [c.source.n, c.source.slug, c.manifest.imageUrls.uniqueTotal, c.manifest.imageUrls.fromDom.length, c.manifest.imageUrls.fromResponses.length, c.kind === 'mealsy' ? `${c.menu.sections.flatMap((s) => s.items).filter((i) => i.photo).length} of ${c.menu.itemCount}` : `${c.categories.flatMap((k) => k.items).filter((i) => i.imgSrc).length} of ${c.categories.flatMap((k) => k.items).length}`, 'none (URLs only)']));

// ---------------------------------------------------------------------------
H('## 6. Known data facts checked against the raw capture');
const kl3 = caps.find((c) => c.source.n === 3), kl4 = caps.find((c) => c.source.n === 4), kl5 = caps.find((c) => c.source.n === 5), se1 = caps.find((c) => c.source.n === 1), se6 = caps.find((c) => c.source.n === 6);
const ok = (c) => c && !c.missing;
if (ok(se6)) {
  const all = se6.categories.flatMap((k) => k.items.map((i) => ({ ...i, cat: k.name, hidden: k.hidden })));
  const juice = all.filter((i) => /juice bar/i.test(i.cat));
  P(`- **Senso listed lines**: sensocafe.ca has ${all.length} item lines in ${se6.categories.length} headings (${all.filter((i) => !i.hidden).length} visible on the phone, ${all.filter((i) => i.hidden).length} inside phone-hidden blocks). Mealsy Senso rendered menu has ${ok(se1) ? se1.menu.itemCount : '?'} items. Combined listed lines: ${all.length + (ok(se1) ? se1.menu.itemCount : 0)}.`);
  const dups = dupNames(all.map((i) => ({ name: i.name, cat: i.cat })));
  P(`- **Senso duplicates across sections (sensocafe.ca)**: ${dups.length} names appear under more than one heading: ${dups.slice(0, 40).map((d) => `${d.name} [${d.cats.join(' + ')}]`).join('; ')}${dups.length > 40 ? ' …' : ''}.`);
  if (ok(se1)) { const d1 = dupNames(se1.menu.sections.flatMap((s) => s.items.map((i) => ({ name: i.name, cat: s.name })))); P(`- **Senso duplicates across sections (Mealsy rendered menu)**: ${d1.length} names: ${d1.map((d) => `${d.name} [${d.cats.join(' + ')}]`).join('; ') || 'none'}.`); }
  const subs = se6.categories.filter((k) => /juice bar ›/i.test(k.name));
  P(`- **Juice and milk lines**: Juice Bar visible base list has ${juice.filter((i) => !i.hidden && !/›/.test(i.cat)).length} entries; the phone-hidden juice blocks hold ${subs.length} sub-headings with ${subs.reduce((a, k) => a + k.items.length, 0)} lines. Sub-headings whose list does not match the heading (mislabeled): ${subs.filter((k) => k.items.length && !k.items.some((i) => norm(i.name).includes(norm(k.name.split('›')[1]).split(' ')[0]))).map((k) => `"${k.name.split('› ')[1]}" lists ${k.items.slice(0, 3).map((i) => i.name).join(', ')}…`).join('; ') || 'none'}. Sub-headings with no list under them (heading only): ${subs.filter((k) => k.emptyList).map((k) => `"${k.subHeading}"${k.items[0]?.description ? ' (has an ingredient line)' : ''}`).join(', ') || 'none'}.`);
}
if (ok(kl5)) {
  const items = kl5.categories.flatMap((k) => k.items.map((i) => ({ ...i, cat: k.name })));
  const v = items.filter((i) => i.variants?.length);
  P(`- **Kebab Land size variants (drinks page)**: ${v.length} items carry size/price variants, e.g. ${v.slice(0, 6).map((i) => `${i.name}: ${i.variants.map((x) => `${x.size} $${x.price}`).join(', ')}`).join('; ')}.`);
}
if (ok(kl4)) {
  const items = kl4.categories.flatMap((k) => k.items.map((i) => ({ ...i, cat: k.name })));
  const serves = items.filter((i) => /serves\s*\d/i.test(i.description || '') || /serves\s*\d/i.test(i.name));
  P(`- **"Serves N" platters (food page)**: ${serves.length} items: ${serves.map((i) => `${i.name} ($${i.prices.join('/')}) — ${((i.description || '') + ' ' + i.name).match(/serves\s*[\d-]+/i)?.[0]}`).join('; ')}.`);
  const KEY = ['barg', 'koobideh', 'koobide', 'chenjeh', 'shishlik', 'sour kebab', 'torsh', 'darbari', 'shekari', 'chicken leg', 'chicken breast', 'saffron chicken', 'mast o mosir', 'mast o moosir', 'zeytoon', 'baba', 'kashke', 'fried eggplant'];
  const combos = items.filter((i) => { const d = norm(i.description || ''), n = norm(i.name); return KEY.some((k) => d.includes(k) && !n.includes(k)); });
  P(`- **Combos built from other items (food page)**: ${combos.length} items whose description names other menu items (keywords: ${KEY.join(', ')}): ${combos.map((i) => `${i.name} (${i.prices.join('/')})`).join('; ')}.`);
}
if (ok(kl3)) {
  const t = kl3.menus.flatMap((m) => m.sections.flatMap((s) => s.items.map((i) => ({ ...i, menu: m.name, sec: s.name }))));
  const combos = t.filter((i) => /combo/i.test(i.name));
  P(`- **Combos in Mealsy Kebab Land**: ${combos.length} items named "…Combo" (${[...new Set(combos.map((i) => i.menu))].join(', ')}), each built from a sandwich item plus a Drinks modifier group, e.g. ${combos.slice(0, 2).map((i) => `${i.name} $${i.price} [${i.modifierGroups.map((g) => `${g.name}: ${g.modifiers.map((m) => m.name).join('/')}`).join('; ')}]`).join('; ')}. Sections with \`Combos\` arrays: ${kl3.menus.flatMap((m) => m.sections).filter((s) => s.combos).length}.`);
  P(`- **Mealsy Kebab Land menus**: ${kl3.menus.map((m) => `"${m.name}" (channels ${m.channels}, ${m.itemCount} items)`).join('; ')}. The rendered online menu is "${kl3.menu.name}".`);
}
// same dish under several names
const nameSets = [['Chenjeh'], ['Sour', 'Torsh', 'Gilaki'], ['Mast', 'Maast', 'Moosir', 'Mousir', 'Moosier', 'Mouseir']];
for (const set of nameSets) {
  const rows = [];
  for (const c of caps.filter(ok)) for (const h of findItems(c, set, true)) { const r = `[${c.source.n}] ${h.name} (${h.price ?? '—'})`; if (!rows.includes(r)) rows.push(r); }
  P(`- **Spellings for ${set[0]}${set.length > 1 ? ' / ' + set.slice(1).join(' / ') : ''}**: ${rows.join('; ') || 'none found'}.`);
}
// drink descriptions
for (const n of ['Fresh Berry Mojito-Virgin', 'Red Wine Sangria', 'Black Russian']) {
  const rows = [];
  for (const c of caps.filter(ok)) for (const h of findItems(c, n)) rows.push(`[${c.source.n}] ${h.name} (${h.price ?? ((h.variants || []).map((v) => `${v.size} ${v.price}`).join(', ') || '—')}): "${h.description ?? 'null'}"`);
  P(`- **${n} description**: ${rows.join('; ') || 'not found'}.`);
}
{
  const rows = [];
  for (const c of caps.filter(ok)) for (const n of ['Mohtasham', 'Soltani']) for (const h of findItems(c, n)) { const r = `[${c.source.n}] ${h.name} ${h.price ?? '—'} — "${h.description ?? 'null'}"`; if (!rows.includes(r)) rows.push(r); }
  P(`- **Mohtasham vs Soltani**: ${rows.join('; ')}.`);
}
for (const c of [kl4, kl5].filter(ok)) P(`- **Tap-to-call links on ${c.source.slug}**: ${c.manifest.observed.links.map((l) => `${l.href.split(':')[0]} link (${l.visibleOnPhone ? 'visible' : 'hidden on phone'}); the number it dials matches the displayed number: ${l.hrefDigitsMatchDisplayed === undefined ? 'not recorded' : l.hrefDigitsMatchDisplayed ? 'yes' : 'NO'} (digits removed from the capture, see manifest.redactions)`).join('; ') || 'none found'}.`);
{
  const rows = [];
  for (const c of caps.filter(ok)) { const txt = (c.html || '').replace(/roseskebablands/gi, ''); const counts = ['Kebab', 'Kabab', 'Kebob', 'Kabob'].map((w) => `${w}: ${(txt.match(new RegExp(w, 'gi')) || []).length}`); rows.push(`[${c.source.n}] ${counts.join(', ')}`); }
  P(`- **Brand spelling in the captured HTML** (case-insensitive counts, the domain name roseskebablands excluded): ${rows.join('; ')}. Mealsy account name: "${kl3?.account?.BusinessAccountName ?? '?'}".`);
}
await fs.writeFile(OUT, md.join('\n') + '\n');
console.log(md.join('\n'));
console.log(`\nReport written to ${OUT}`);

// ===========================================================================
async function load(source, dir, manifest) {
  const c = { source, dir, manifest, kind: source.kind };
  try { c.html = await fs.readFile(path.join(dir, 'html/index.html'), 'utf8'); } catch { c.html = ''; }
  if (source.kind === 'mealsy') {
    const menuEntry = manifest.files.find((f) => f.type === 'decoded' && /dataCategory=1\b/.test(f.url));
    if (!menuEntry) throw new Error('no decoded dataCategory=1 payload in manifest');
    c.menuFile = menuEntry.path; c.menuRawFile = menuEntry.derivedFrom; c.decodedMenuSha = menuEntry.sha256;
    const payload = JSON.parse(await fs.readFile(path.join(dir, menuEntry.path), 'utf8'));
    c.menus = payload.Menus.map((m) => ({
      id: m.Id, name: lang(m.NameOnline) || lang(m.Name), channels: m.OrderChannels, isDefault: m.IsDefaultOnlineMenu, status: m.Status,
      sections: m.MenuSections.map((s) => ({
        id: s.Id, name: lang(s.NameOnline) || lang(s.Name), status: s.Status, position: s.Position, combos: (s.Combos || []).length || 0,
        items: s.MenuItems.map((i) => ({
          id: i.Id, name: lang(i.NameOnline) || lang(i.Name), rawName: i.Name, variant: lang(i.VariantName), price: i.Price, rawPrice: i.Price,
          description: lang(i.Description), rawDescription: i.Description ?? null, information: lang(i.Information), photo: lang(i.PhotoPathOnline), status: i.Status, position: i.Position,
          modifierGroups: (i.ModifierGroups || []).map((g) => ({ name: lang(g.Name), type: g.ModifierType, min: g.MinPermittedModifiers, modifiers: (g.Modifiers || []).map((x) => ({ name: lang(x.Name), price: x.Price })) })),
          raw: i,
        })),
      })),
    }));
    for (const m of c.menus) m.itemCount = m.sections.reduce((a, s) => a + s.items.length, 0);
    c.observedSections = manifest.observed.sections || [];
    c.observedTitles = c.observedSections.map((s) => s.title);
    c.observedNav = manifest.observed.categoryNav || [];
    const screenNames = c.observedSections.flatMap((s) => s.items.map((i) => norm(i.name)));
    let best = null;
    for (const m of c.menus) {
      const matched = c.observedTitles.filter((t) => m.sections.some((s) => norm(s.name) === norm(t))).length;
      const names = new Set(m.sections.flatMap((s) => s.items.map((i) => norm(i.name))));
      const itemsMatched = screenNames.filter((n) => names.has(n)).length;
      if (!best || matched + itemsMatched > best.matched + best.itemsMatched) best = { menu: m, matched, itemsMatched };
    }
    c.menu = best.menu; c.menuMatch = best; c.screenNames = screenNames;
    const menuNames = new Set(c.menu.sections.flatMap((s) => s.items.map((i) => norm(i.name))));
    c.dataNotOnScreen = c.menu.sections.flatMap((s) => s.items.filter((i) => !screenNames.includes(norm(i.name))).map((i) => ({ section: s.name, item: i })));
    c.screenNotInData = c.observedSections.flatMap((s) => s.items.filter((i) => !menuNames.has(norm(i.name))).map((i) => `${s.title} › ${i.name}`));
    const acct = manifest.files.find((f) => f.type === 'response' && /BusinessAccounts\?xRefCode/.test(f.url));
    c.account = acct ? JSON.parse(await fs.readFile(path.join(dir, acct.path), 'utf8')) : {};
    const avail = manifest.files.find((f) => f.type === 'decoded' && /dataCategory=2\b/.test(f.url));
    if (avail) { const a = JSON.parse(await fs.readFile(path.join(dir, avail.path), 'utf8')); const ids = new Set(c.menu.sections.flatMap((s) => s.items.map((i) => i.id))); c.availabilityIds = new Set((a.MenuItemSalesAvailabilities || []).map((x) => x.ProductItemId)); c.availability = { items: (a.MenuItemSalesAvailabilities || []).length, modifiers: (a.ModifierSalesAvailabilities || []).length, matched: (a.MenuItemSalesAvailabilities || []).filter((x) => ids.has(x.ProductItemId)).length }; }
  } else {
    c.categories = source.n === 6 ? parseSenso(manifest.observed.widgets) : parseRoses(manifest.observed.widgets);
  }
  return c;
}

// roseskebablands.com: heading = category; text-editor lines = "Name $price", variant lines, descriptions.
function parseRoses(widgets) {
  const cats = []; let cat = null; let last = null;
  const PRICE = /\$\s?(\d+(?:\.\d{1,2})?)/g;
  const VARIANT = /^(?:\d+(?:\.\d+)?\s*oz|1-shot|shot|bottle|serves)/i;
  const VPAIR = /(\d+(?:\.\d+)?\s*oz|1-shot|bottle)\s*\$\s?(\d+(?:\.\d{1,2})?)/gi;
  for (let n = 0; n < widgets.length; n++) {
    const w = widgets[n];
    if (w.type.startsWith('heading')) { cat = { name: w.text.replace(/[╔╗]/g, '').trim(), hidden: !w.visibleOnPhone, items: [], notes: [] }; cats.push(cat); last = null; continue; }
    if (!w.type.startsWith('text-editor') || !cat) continue;
    const text = w.text; const prices = [...text.matchAll(PRICE)].map((m) => m[1]);
    const next = widgets[n + 1];
    if (VARIANT.test(text) && prices.length && last && last.pendingVariants) { last.variants = [...text.matchAll(VPAIR)].map((m) => ({ size: m[1].trim(), price: m[2] })); last.prices = prices; last.variantLine = text; last.pendingVariants = false; continue; }
    if (prices.length && text.length <= 90) { last = { name: text.replace(/\s*\$\s?\d+(?:\.\d{1,2})?\s*$/, '').trim(), prices, raw: text, description: null, hidden: !w.visibleOnPhone, imgSrc: null }; cat.items.push(last); continue; }
    if (!prices.length && next && next.type.startsWith('text-editor') && VARIANT.test(next.text) && /\$/.test(next.text)) { last = { name: text.trim(), prices: [], raw: text, description: null, hidden: !w.visibleOnPhone, pendingVariants: true, imgSrc: null }; cat.items.push(last); continue; }
    if (last) last.description = last.description ? `${last.description} | ${text}` : text; else cat.notes.push(text);
  }
  return cats;
}

// sensocafe.ca: visible heading = category; hidden heading = sub-group (desktop-only block); icon-list/price-list entries = items.
function parseSenso(widgets) {
  const cats = []; let top = null; let cur = null;
  for (const w of widgets) {
    if (/©|Privacy Policy|Designed and Developed/i.test(w.text)) continue;
    if (w.type.startsWith('heading')) {
      if (/^our menu$/i.test(w.text)) continue;
      if (w.visibleOnPhone) { top = { name: w.text, hidden: false, items: [], notes: [] }; cats.push(top); cur = top; }
      else if (top) { cur = { name: `${top.name} › ${w.text}`, hidden: true, items: [], notes: [], subHeading: w.text }; cats.push(cur); }
      continue;
    }
    if (!cur) continue;
    if (w.type.startsWith('icon-list')) for (const t of w.items || []) cur.items.push({ name: t, prices: [], raw: t, description: null, hidden: !w.visibleOnPhone, imgSrc: null });
    else if (w.type.startsWith('price-list')) for (const it of w.items || []) cur.items.push({ name: it.title, prices: it.price && /\d/.test(it.price) ? [it.price.replace(/[^\d.]/g, '')] : [], raw: `${it.title} [${it.price || ''}] ${it.description || ''}`.trim(), description: it.description || null, hidden: !w.visibleOnPhone, imgSrc: it.imgSrc });
    else if (w.type.startsWith('text-editor') && w.text) { if (cur.subHeading && !cur.items.length) cur.notes.push(w.text); else cur.notes.push(w.text); }
  }
  // a hidden sub-heading with no list is itself the item (e.g. "Watermelon Juice")
  for (const k of cats) if (k.subHeading && !k.items.length) { k.items.push({ name: k.subHeading, prices: [], raw: k.subHeading, description: k.notes.join(' ') || null, hidden: true, imgSrc: null }); k.notes = []; k.emptyList = true; }
  return cats;
}

function findItems(c, needle, loose = false) {
  const needles = (Array.isArray(needle) ? needle : [needle]).map(norm);
  const hit = (name) => { const n = norm(name); return loose ? needles.some((x) => n.includes(x)) : needles.some((x) => n === x || n.startsWith(x + ' ') || n.includes(' ' + x) || n.includes(x)); };
  const out = [];
  if (c.kind === 'mealsy') {
    for (const m of c.menus) for (const s of m.sections) for (const i of s.items) if (hit(i.name)) out.push({ name: i.name, price: i.price, description: i.description, where: `menu "${m.name}" › section "${s.name}" (file \`${c.menuFile}\`)`, lang: 'json', verbatim: JSON.stringify({ Name: i.raw.Name, Price: i.raw.Price, Description: i.raw.Description ?? null, VariantName: i.raw.VariantName ?? null, ModifierGroups: (i.raw.ModifierGroups || []).map((g) => ({ Name: g.Name, Modifiers: g.Modifiers.map((x) => ({ Name: x.Name, Price: x.Price })) })) }, null, 2) });
  } else {
    for (const k of c.categories) for (const i of k.items) if (hit(i.name)) out.push({ name: i.name, price: i.prices.length === 1 ? i.prices[0] : (i.prices.length ? i.prices.join('/') : null), variants: i.variants, description: i.description, where: `heading "${k.name}"${k.hidden || i.hidden ? ' (hidden on phone)' : ''} (file \`html/index.html\`, widget text)`, lang: 'text', verbatim: [i.raw, i.variantLine, i.description].filter(Boolean).join('\n') });
  }
  return out;
}

function dupNames(list) {
  const m = new Map();
  for (const x of list) { const k = norm(x.name); if (!k) continue; if (!m.has(k)) m.set(k, { name: x.name, cats: new Set() }); m.get(k).cats.add(x.cat); }
  return [...m.values()].filter((v) => v.cats.size > 1).map((v) => ({ name: v.name, cats: [...v.cats] }));
}
function sameDish(a, b) { const x = norm(a).replace(/\bkebab\b/g, '').trim(), y = norm(b).replace(/\bkebab\b/g, '').trim(); return x === y; }
function lang(s) { if (s == null) return null; if (typeof s !== 'string') return s; try { const j = JSON.parse(s); if (j && typeof j === 'object') return j.En ?? Object.values(j).find((v) => v != null) ?? null; return s; } catch { return s; } }
function norm(s) { return String(s ?? '').normalize('NFKD').replace(/[؀-ۿ‌]+/g, ' ').replace(/[’'`´]/g, '').replace(/[^a-z0-9]+/gi, ' ').trim().toLowerCase(); }
async function latestDate() { const dates = new Set(); for (const s of SOURCES) { try { for (const d of await fs.readdir(path.join(RAW, s.slug))) if (/^\d{4}-\d{2}-\d{2}$/.test(d)) dates.add(d); } catch {} } return [...dates].sort().pop(); }
function parseArgs(argv) { const out = {}; for (let i = 0; i < argv.length; i++) if (argv[i].startsWith('--')) out[argv[i].slice(2)] = argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[++i] : true; return out; }
