// Writes import-report.md: spelling fixes, known factual errors imported as-is, unpriced items, Persian drafts,
// plus placements, website descriptions used, venue details to confirm and brand sources.
import fs from 'node:fs/promises';
import path from 'node:path';

export async function writeReport({ venue, date, out, data, venues, counts }) {
  const L = data.log, md = [];
  const H = (s) => md.push('', s, '');
  const P = (s) => md.push(s);
  const T = (head, rows) => { md.push('| ' + head.join(' | ') + ' |', '| ' + head.map(() => '---').join(' | ') + ' |'); for (const r of rows) md.push('| ' + r.map((c) => String(c ?? '').replace(/\|/g, '\\|')).join(' | ') + ' |'); };
  const secName = (k) => data.sections.find((s) => s.importKey === k)?.name.en;
  H(`# Import report — ${venue} — ${date}`);
  P(`Generated by \`tools/import/run.mjs ${venue}\` from \`data/raw/*/${date}/\`. Source labels appear in this internal file only.`);
  P('');
  T(['Sections', 'Items', 'From the primary source', 'Listed (priced)', 'Unlisted (needs price)', 'Website names read', 'Website names matched to primary items'],
    [[data.stats.sections, data.stats.items, data.stats.mealsyItems, data.stats.listed, data.stats.unlisted, data.stats.websiteNames, data.stats.websiteMatched]]);
  if (counts) { P(''); P(`Database load: sections +${counts.sectionsInserted} updated ${counts.sectionsUpdated} kept ${counts.sectionsKept}; items +${counts.itemsInserted} updated ${counts.itemsUpdated} kept ${counts.itemsKept} (kept = already edited by an admin, left untouched).`); }
  P('');
  P('Per section (listed / unlisted):');
  P('');
  T(['Section', 'Listed', 'Unlisted'], data.sections.map((s) => [s.name.en, data.items.filter((i) => i.listed && i.placements.some((p) => p.section === s.importKey)).length, data.items.filter((i) => !i.listed && i.placements.some((p) => p.section === s.importKey)).length]));

  H('## 1. Spelling fixes (before → after)');
  P('Only misspelled English words and whitespace/title-case cleanups; transliterations of Persian words are never changed.');
  P('');
  T(['Source', 'Before', 'After', 'Kind'], L.fixes.map((f) => [f.source, f.before, f.after, f.kind || 'spelling']));

  H('## 2. Known factual errors and oddities, imported as-is');
  for (const o of L.oddities) P(`- ${o}`);
  for (const m of L.mergedPlacements) P(`- "${m.item}" is listed in two sections by the source (${m.sections.join(' and ')}) at the same price: imported once, shown in both.`);

  H('## 3. Unpriced items (imported unlisted, "needs price")');
  P(`${L.unlisted.length} website-only names have no price in any source. They are unlisted and show only in the admin until priced and listed.`);
  P('');
  T(['Item', 'Placed in section', 'Website heading'], L.unlisted.map((u) => [u.item, u.section, u.websiteHeading]));

  H('## 4. Persian');
  P(`Split from the source strings: ${L.persian.fromSource.length}. Drafted: ${L.persian.drafted.length}. Missing (falls back to English): ${L.persian.missing.length}.`);
  P('');
  P('Drafts are machine/agent drafts flagged per field (`fa_draft`); the owner reviews them in the admin.');
  P('');
  T(['What', 'Field', 'English', 'Persian (draft)'], L.persian.drafted.map((d) => [d.what, d.field, d.en, d.fa]));
  if (L.persian.missing.length) { P(''); P('Not drafted (unlisted website-only items; English fallback until priced and listed):'); P(''); T(['What', 'Field', 'English'], L.persian.missing.map((d) => [d.what, d.field, d.en])); }

  H('## 5. Placements of website names (every one can be moved in the admin)');
  P(`Website headings were mapped to sections by meaning. New sections created: ${L.newSections.join(', ') || 'none'}.`);
  P('');
  T(['Website name', 'Website heading', 'Section', 'Note'], L.placements.map((p) => [p.item, p.websiteHeading, p.section, p.note || '']));
  P('');
  P(`Website names matched to primary-source items (no new item created): ${L.matches.length}. Juice names matched by meaning ("X Juice" ↔ "X" in Fresh Juice): ${L.juiceMatches.map((j) => `${j.website} ↔ ${j.mealsy}`).join('; ') || 'none'}.`);

  H('## 6. Website descriptions used (primary-source description was empty)');
  T(['Item', 'Description'], L.descriptionsFromWebsite.map((d) => [d.item, d.description]));

  if (venues) {
    H('## 7. Venue details, prefilled — every line is "to confirm"');
    T(['Field', 'Value', 'Source'], venues.sources.map((s) => [s.field, s.value, s.source]));
    H('## 8. Brand: colours and fonts with their sources');
    T(['Token', 'Value', 'Source'], venues.brand.sources.map((s) => [s.token, s.value, s.source]));
  }
  await fs.writeFile(path.join(out, 'import-report.md'), md.join('\n') + '\n');
}
