import type { GetStaticPaths, GetStaticProps } from 'next';
import Head from 'next/head';
import { getPublicMenu, getVenue, getVenues } from '@/lib/menu';
import type { Section, Venue } from '@/lib/types';
import { Intro, headScript } from '@/components/Intro';
import { DefaultPage } from '@/venues/default';
import { styleOf } from '@/venues/styles';

// Venues added in the admin ("+ Add venue", step 2): their page on the default template (src/venues/default.tsx).
// Senso and Kebab Land keep their own files (src/pages/senso.tsx, kebab-land.tsx); a static route always wins over
// this dynamic one, and this page answers 404 for them. New venues are rendered on their first request and then
// regenerated by an admin save like the others (res.revalidate). Plain HTML, no framework JavaScript.
export const config = { unstable_runtimeJS: false, runtime: 'nodejs' };

const SYSTEM = "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif";
type Props = { venue: Venue; sections: Section[] };

export const getStaticPaths: GetStaticPaths = async () => ({
  paths: (await getVenues()).filter((v) => v.template === 'default').map((v) => ({ params: { venue: v.id } })),
  fallback: 'blocking',
});

export const getStaticProps: GetStaticProps<Props, { venue: string }> = async ({ params }) => {
  const id = params?.venue ?? '';
  if (!/^[a-z0-9-]{1,40}$/.test(id)) return { notFound: true };
  const venue = await getVenue(id);
  if (!venue || venue.template !== 'default') return { notFound: true };
  const sections = await getPublicMenu(id, venue.settings?.showPersianDrafts !== false);
  return { props: JSON.parse(JSON.stringify({ venue, sections })) };
};

export default function VenuePage({ venue, sections }: Props) {
  const style = styleOf(venue);
  const vars = `:root{--brand-bg:#ffffff;--brand-fg:#1d1d1f;--brand-accent:${style.accent};--brand-muted:#6e6e73;--brand-tile:${style.tile};--font-heading:${SYSTEM};--font-body:${SYSTEM};--font-persian:var(--font-vazirmatn), system-ui, sans-serif}`;
  return (
    <>
      <Head>
        <title>{`${venue.name.en} — Menu`}</title>
        <meta name="description" content={venue.tagline.en ?? `${venue.name.en} menu`} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#ffffff" />
        {venue.brand.logo && <link rel="icon" href={venue.brand.logo.url} />}
        <script dangerouslySetInnerHTML={{ __html: headScript() }} />
      </Head>
      <style dangerouslySetInnerHTML={{ __html: vars }} />
      {style.intro !== false && venue.brand.logo && <Intro logo={venue.brand.logo} alt={venue.name.en ?? ''} tile={String(style.tile)} />}
      <DefaultPage venue={venue} sections={sections} style={style} />
    </>
  );
}
