// Serves uploaded files (/uploads/<venue>/<kind>-<uuid>.<ext> is rewritten here, see next.config.ts). Keys are
// generated by the app, so anything not matching the key pattern is 404. Long cache: a key is never reused.
import type { NextApiRequest, NextApiResponse } from 'next';
import { storage } from '@/lib/storage';

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'GET' && req.method !== 'HEAD') { res.setHeader('Allow', 'GET, HEAD'); res.status(405).end(); return; }
  const key = (Array.isArray(req.query.key) ? req.query.key : [req.query.key ?? '']).join('/');
  const file = await storage.get(key);
  if (!file) { res.status(404).end(); return; }
  res.setHeader('Content-Type', file.contentType);
  res.setHeader('Content-Length', String(file.body.length));
  res.setHeader('Cache-Control', 'public, max-age=31536000, immutable');
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.setHeader('Content-Security-Policy', "default-src 'none'; sandbox"); // an uploaded SVG opened on its own runs nothing
  if (req.method === 'HEAD') { res.status(200).end(); return; }
  res.status(200).end(file.body);
}
